### PR TITLE
move logic to action file

### PR DESCRIPTION
**Pull request by JisanAR03**
work : before run the assign function, we just check the comment body and behalf of this, run the assign function , so it's fixed issue #10 and #11

Note: To apply these changes in BLT, we have to update the workflow file in BLT, and for this, please approve PR: https://github.com/OWASP/BLT/pull/1753

### CODE REVIEW

**Comment by JisanAR03** [comment]
> I would like to see some kind of automated tests

@fredfalcon  sir , then we have to use the workflow in a dummy project. I will create one and give you the link for test

**Comment by DonnieBLT** [comment]
@JisanAR03 can you use this project as the test project? So it is self contained?

**Comment by JisanAR03** [comment]
> @JisanAR03 can you use this project as the test project? So it is self contained?
@DonnieBLT sir, sorry for asking again. Can you explain a little bit more detailly?

**Comment by DonnieBLT** [comment]
@JisanAR03 you mentioned having a test project so can you use this repository to have the test project?  Ideally we can have a github action in this repository that can test creating an issue adding "/ assign" to it and see if it gets assigned to the user?  or if there was a way to make the code more modular and test individual functions that might work too.  My main concern is that we have some automated test to make sure it always works.

**Comment by JisanAR03** [comment]
> @JisanAR03 you mentioned having a test project so can you use this repository to have the test project? Ideally we can have a github action in this repository that can test creating an issue adding "/ assign" to it and see if it gets assigned to the user? or if there was a way to make the code more modular and test individual functions that might work too. My main concern is that we have some automated test to make sure it always works.

@DonnieBLT sir, then I think I should update this PR with the workflow file. and then you can check here. Is it ok, sir?

**Comment by JisanAR03** [comment]
@DonnieBLT  , actually, sir I only added few lines of code but for the "if (issue && proceedWithIssueProcessing) {" line, github shows I edited all of the code 🙂

`if (eventName === 'issue_comment' && issue && comment) {
        console.log('processing issue comment');
        const commentBody = comment.body.toLowerCase(); // Convert to lower case for case-insensitive comparison
        const assignKeywords = ['/assign', 'assign to me', 'assign this to me', 'please assign me this', 'i can try fixing this', 'i am interested in doing this', 'i am interested in contributing'];
        const unassignKeywords = ['/unassign'];

        const shouldAssign = assignKeywords.some(keyword => commentBody.includes(keyword));
        const shouldUnassign = unassignKeywords.some(keyword => commentBody.startsWith(keyword));

        if (shouldAssign) {
            proceedWithIssueProcessing = true; // Set flag to true
        } else if (shouldUnassign) {
            console.log(`Unassigning issue #${issue.number} from ${comment.user.login}`);
            await octokit.issues.removeAssignees({
                owner,
                repo,
                issue_number: issue.number,
                assignees: [comment.user.login]
            });
        }
    }`

**Comment by DonnieBLT** [comment]
ok let's go with it, thanks.  hopefully everything continues to work.  Can you please test after it's merged?

**Review by DonnieBLT — APPROVED** [review]

**Comment by JisanAR03** [comment]
@DonnieBLT  , thank you so much sir ☺

**Comment by JisanAR03** [comment]
> ok let's go with it, thanks. hopefully everything continues to work. Can you please test after it's merged?

yeah sir sure .. I will test this after merge the "BLT" pr

**Comment by JisanAR03** [comment]
screenshot after test: 
image
image
image


looks fine sir ☺

**Comment by DonnieBLT** [comment]
awesome, nice work, thanks!

**Comment by DonnieBLT** [comment]
Can you please also update the readme

**Comment by JisanAR03** [comment]
> Can you please also update the readme

yeah sir sure , I will make one more PR after update the Readme

**Pull request merged**
